# Generated by Django 4.2.3 on 2023-07-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='Cartitem',
        ),
    ]
